name: class
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - rbase=4.0
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-plotly
  - r-stringr 
  - pip
  - pip:
   - plotly
   - matplotlib
   - numpy
   - pandas
   - scikit-learn
